### ISSUE TITLE
Replacing Mosek with OSQP

### ISSUE THREAD

**Issue by andrewcztrack** [cvxgrp/strat_models#3]
Hi @jonathantuck @sbarratt !!

Would it be possible to replace mosek solver with OSQP for the finance sector example?

Also, i would like to add a constraint that every weight is above 5%, would this be possible?

Kind regards and thanks,
Andrew

**Comment by sbarratt** [comment]
We don’t use MOSEK or OSQP in this project

**Comment by andrewcztrack** [comment]
Hi @sbarratt !!

Thank you for your help :)!


When i run the sector example i get the below -

In the training set:
        Market conditions average of 1.2664 data points.
        The most populated market condition has 38 data points.
        1395 market conditions have no data.
Traceback (most recent call last):
  File "sectors.py", line 91, in <module>
    prob.solve(verbose=False)
  File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 753, in _solve
    self, data, warm_start, verbose, kwargs)
  File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 326, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py", line 233, in solve_via_data
    task.optimize()
  File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/mosek/__init__.py", line 7627, in optimize
    raise Error(rescode(res),msg)
mosek.Error: rescode.err_missing_license_file(1008): License cannot be located. The default search path is ':/home/andrewcz/mosek/mosek.lic:

I assume its because i don't have a licence for mosek.

**Comment by jonathantuck** [comment]
Hello! Unfortunately, this problem cannot be reduced to a QP, so you cannot use OSQP for this optimization problem.

Best,
Jonathan

On Nov 25, 2020, at 8:00 PM, andrewcztrack <notifications@github.com> wrote:

﻿

Hi @sbarratt<https://github.com/sbarratt> !!

When i run the sector example i get the below -

In the training set:
Market conditions average of 1.2664 data points.
The most populated market condition has 38 data points.
1395 market conditions have no data.
Traceback (most recent call last):
File "sectors.py", line 91, in
prob.solve(verbose=False)
File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 396, in solve
return solve_func(self, *args, **kwargs)
File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 753, in _solve
self, data, warm_start, verbose, kwargs)
File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 326, in solve_via_data
solver_opts, problem._solver_cache)
File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py", line 233, in solve_via_data
task.optimize()
File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/mosek/init.py", line 7627, in optimize
raise Error(rescode(res),msg)
mosek.Error: rescode.err_missing_license_file(1008): License cannot be located. The default search path is ':/home/andrewcz/mosek/mosek.lic:

**Comment by andrewcztrack** [comment]
Hi @jonathantuck @sbarratt !!

Thank you! much appreciated!
Is there an open source solver that can I can use for the optimisation?

@jonathantuck  is there anyway to make the weights a minimum of 5% for example, so as to get non-zero weights in the optimisation?

Kind regards and thanks,
Andrew

**Comment by jonathantuck** [comment]
You must use a solver that can handle SDPs. SCS is an open-source solver that you could use. For a full list compatible with CVXPY, see [here](https://www.cvxpy.org/tutorial/advanced/index.html). 

I'm not entirely sure what you're asking about in your second question. Could you clarify?

**Comment by andrewcztrack** [comment]
Hi @jonathantuck !

Thank you! In terms of changing the solver, do i just have to change these two lines?

```python
    prob = cp.Problem(cp.Minimize(obj), cons_sm)
    prob_common = cp.Problem(cp.Minimize(obj_common), cons_common)
    
    prob.solve(solver="SCS") 
    prob_common.solve(solver="SCS") 

```

So I was wondering if could set a constraint for the optimization, that every weight of the portfolio has to be at least 5% of the original capital ie no weight of the solved optimization is less than 5%.

Kind regards and sincere thanks,
Andrew

**Comment by andrewcztrack** [comment]
Hi @jonathantuck !! I hope your well.

i tried replacing the above code and got the below output -

```python
(mlfinll) [andrewcz@andrewcz examples]$ ls
__pycache__  cardio.py  crime.py  data  elections.py  figs  house.py  mesothelioma.py  sectors.py  utils.py  weather.py
(mlfinll) [andrewcz@andrewcz examples]$ python sectors.py 
In the training set:
        Market conditions average of 1.2664 data points.
        The most populated market condition has 38 data points.
        1395 market conditions have no data.
Traceback (most recent call last):
  File "sectors.py", line 91, in <module>
    prob.solve(verbose=False)
  File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 753, in _solve
    self, data, warm_start, verbose, kwargs)
  File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 326, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py", line 233, in solve_via_data
    task.optimize()
  File "/home/andrewcz/miniconda3/envs/mlfinll/lib/python3.7/site-packages/mosek/__init__.py", line 7627, in optimize
    raise Error(rescode(res),msg)
mosek.Error: rescode.err_missing_license_file(1008): License cannot be located. The default search path is ':/home/andrewcz/mosek/mosek.lic:'.
(mlfinll) [andrewcz@andrewcz examples]$ 
```

**Comment by jonathantuck** [comment]
Based on your error message, you are still using MOSEK as your solver, it looks like you did not replace
`prob.solve(verbose=False)` with `prob.solve(verbose=False, solver="SCS")` on line 91.

**Comment by andrewcztrack** [comment]
@jonathantuck It worked!! thank you :)!
